drenso_oidc:
  clients:
    administrator: # The client name, each client will be aliased to its name (for example, $administratorOidcClient)
      well_known_url: '%env(OIDC_WELL_KNOWN_URL)%'
      client_id: '%env(OIDC_CLIENT_ID)%'
      client_secret: '%env(OIDC_CLIENT_SECRET)%'
      redirect_route: '/admin/login_check'
