security:
  providers:
    administrator:
      id: App\Security\Administrator\AdministratorProvider
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    administrator_secured_area:
      pattern: /admin
      context: main
      provider: administrator
      user_checker: App\Security\UserChecker
      access_denied_url: admin_access_denied
      oidc:
        client: administrator
        login_path: administrator_login_oidc
        check_path: administrator_login_check
        user_identifier_property: '%oidc_user_identifier_property%'
        enable_end_session_listener: true
        user_identifier_from_idtoken: '%oidc_user_identifier_from_id_token%'
      logout:
        path: administrator_logout
        target: home

  access_control:
    # Admin area
    - { path: ^/admin/login_oidc, role: PUBLIC_ACCESS }
    - { path: ^/admin/logout$, role: PUBLIC_ACCESS }
    - { path: ^/admin/login_check, role: PUBLIC_ACCESS }
    - { path: ^/admin/forbidden$, role: PUBLIC_ACCESS }
    - { path: ^/admin, role: ROLE_SUPER_ADMIN }

  role_hierarchy:
    ROLE_USER: PUBLIC_ACCESS
    ROLE_ADMIN: ROLE_USER
    ROLE_SUPER_ADMIN: ROLE_ADMIN
