twig:
  default_path: '%kernel.project_dir%/templates'
  file_name_pattern: '*.twig'
  form_themes: ['bootstrap_5_layout.html.twig']
  globals:
    locales:
      - fr
    app_name: '%app_name%'

when@test:
  twig:
    strict_variables: true
