FROM illuin/symfony-ready:8.2-node-20 AS assets_dev

WORKDIR /app

ENV NODE_ENV=dev
ENV PATH=/app/node_modules/.bin:$PATH

RUN apk update && apk upgrade && \
    apk add --no-cache git python3 make g++

ENTRYPOINT  ["/bin/bash", "-c"]
CMD ["npm install && npm run watch"]

# run dev web server
FROM nginx:1.25-alpine3.19 AS nginx_dev

RUN apk update && apk upgrade && apk add --no-cache openssl && \
    openssl req -x509 -nodes -days 365 -subj "/C=CA/ST=QC/O=CentraleSupélec, Inc./CN=aristote-plume-local.centralesupelec.fr" -addext "subjectAltName=DNS:aristote-plume-local.centralesupelec.fr" -newkey rsa:2048 -keyout /usr/share/new-selfsigned.key -out /usr/share/new-selfsigned.crt

WORKDIR /app/public

COPY docker/nginx/default-dev.conf.template /etc/nginx/templates/default.conf.template
