FROM illuin/symfony-ready:8.4-node-22 AS assets_dev

WORKDIR /app

ENV NODE_ENV=dev
ENV PATH=/app/node_modules/.bin:$PATH

RUN apt-get update -q -y \
    && apt-get upgrade -q -y \
    && apt-get install -q -y git python3 g++ \
    && apt-get autoremove && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT  ["/bin/bash", "-c"]
CMD ["npm install && npm run watch"]

# run dev web server
FROM nginx:1.25-alpine3.19 AS nginx_dev

RUN apk update && apk upgrade && apk add --no-cache openssl && \
    openssl req -x509 -nodes -days 365 -subj "/C=CA/ST=QC/O=CentraleSupélec, Inc./CN=aristote-plume-local.centralesupelec.fr" -addext "subjectAltName=DNS:aristote-plume-local.centralesupelec.fr" -newkey rsa:2048 -keyout /usr/share/new-selfsigned.key -out /usr/share/new-selfsigned.crt

WORKDIR /app/public

COPY docker/nginx/default-dev.conf.template /etc/nginx/templates/default.conf.template
